# Generated by Django 5.1.2 on 2024-11-23 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.AddField(
            model_name='organization',
            name='director',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_director', to='myapp.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='participants', to='myapp.section'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('coach', 'Тренер'), ('client', 'Клиент'), ('director', 'Руководитель')], max_length=10),
        ),
    ]
