# Generated by Django 5.1.2 on 2024-11-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_organization_address_organization_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='end_time',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AddField(
            model_name='section',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
